[development]
DB_ENV = "zipdrug-development-db"
SQS_REMOVED_ZIPCODE_INPUT_NAME= "RemoveZipcodeInQueue"
SNS_REMOVED_ZIPCODE_OUTPUT_NAME= "RemoveZipcodeOutTopic2"

[stage]
DB_ENV = "zipdrug-stage-db"
SQS_REMOVED_ZIPCODE_INPUT_NAME= "SampleStgQueue"

[production]
DB_ENV = "production-api-db"
SQS_REMOVED_ZIPCODE_INPUT_NAME= "SampleProdQueue"

